@startsalt
{
                                                            <b><size:15>Packing Cost Comparison
  ==
  {#
    |.|<b><size:17>Part No                    |.  |^<b><size:20>                               ^|^<b><size:20>                                    ^|.|*
    |.|<b><size:17>Periode                    |.  |^<b><size:17>                               ^|^<b><size:17>                                    ^|.|*
    |<size:15> <&chevron-bottom>     |<b>Detail           |  .| .                 | .             |   <b>Diff|*
    |.|<b>Part Name                  |.  |                                   |                                         |.|*    
    |.|<b>Supplier                   |.  |                                   |                                         |.|*        
    |          .                  |<b>TOTAL COST            | : |<b> 0              |<b> 0          |<b>0% |*    
    |<size:15> <&chevron-bottom>  |<b>Material              | : | 0                 | 0                |0%     |*
    |.                            |<&chevron-bottom><b> Inner              | : | 0                 | 0                |0%     |*
    .|{#
        |   |<&chevron-right> Material 1    	               |:  |	                                                                  |	                                                                            |0%        |*
      }|*|*|*|*|*      
      .|.|{ /' Cell 1'/
        .|*
        .|*
        .|*
        .|*
      }|*|{ /' Cell 2'/
        .|*
        .|*
        .|*
        .|*
      }|*
    .|{#
        |   |<&chevron-right> Material 2    	               |:  |                                                                   |	                                                                            |0%         |*
      }|*|*|*|*|*
      .|.|{ /' Cell 1'/
        .|*
        .|*
        .|*
        .|*
      }|*|{ /' Cell 2'/
        .|*
        .|*
        .|*
        .|*
      }|*
    .|{#
    |   |<&chevron-right> Material 3   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 4   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 5   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 6   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 7   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 8   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 9   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 10  |:  |	                                                                  |	                                                                            |0%          |*
  }|*|*|*|*|*
    |.                            |<&chevron-bottom><b> Outer              | : |                      |                     |0%     |*
    .|{#
        |   |<&chevron-right> Material 1    	               |:  |	                                                                  |	                                                                            |0%  |*
      }|*|*|*|*|*      
      .|.|{ /' Cell 1'/
        .|*
        .|*
        .|*
        .|*
      }|*|{ /' Cell 2'/
        .|*
        .|*
        .|*
        .|*
      }|*    
    .|{#
    |   |<&chevron-right> Material 2   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 3   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 4   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 5   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 6   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 7   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 8   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 9   |:  |	                                                                  |	                                                                            |0%          |*
    |   |<&chevron-right> Material 10  |:  |	                                                                  |	                                                                            |0%          |*
  }|*|*|*|*|*      
    |<size:15> <&chevron-right>  |Labor                 |:  |                     |                  |0%  |*      
    |<size:15> <&chevron-right>   |Inland                | : |.                    |  .              |0%  |*    
  }
  
}
@endsalt