@startsalt
{
  <size:15><b>Part List | [<size:25><&x>]|*
  ==
  {
    .|Part No       |: |"           "|[<&magnifying-glass>]|*
    .|Unique No     |: |"           "|*
    .|Supplier ID   |: |"           "| [<&magnifying-glass>]|*
    .|Supplier Name |: |. |*
    .|Parent Part   |: |"           "|[<&magnifying-glass>]|*
    .|Has Subparts?           |: | { ^Yes^No^ } |*  |.|[Search] |*| [Clear]

  }
  {
  .
  }
  --
  {
  [Add Part <&document>] |.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    |<b> Part No    |<b> Suffix | <b>Unique No | <b> Name    |<b> Supplier Name |<b> Parent Part No |<b> Subparts |<b> L |<b> W |<b> H |<b> Qty/Box |<b> Total Wt |<b> Action |*|*|*|*|*|*|*
  }
  No Data Found
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }  
}
@endsalt
