@startsalt
{
  <size:15><b>Model List |[<size:25><&x>]|*
  ==
  .
  {
      .|Model Code        |: |"               "|*
      .|Model Name  |: |"               "|*
      .|Remark      |: |"               "|.|.|[Filter <&magnifying-glass>]| [Clear <&x>]|*
  }
  .
  --
  {
  [Add New Model <&document>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|* 
  }
  --
  {#
    |<b> Model Code |<b>            Model Name      |<b> Remark     |<b> Action |*|*|*
    |  188D         | Hilux                         | 8th Gen       |[<&pencil>]|[<&delete>]|*
    |  975W         | Fortuner                      | 2nd Gen       |[<&pencil>]|[<&delete>]|*
    |  758W         | Corolla Altis                 | 11th Gen      |[<&pencil>]|[<&delete>]|*
    |  303D         | Yaris Gazoo Racing Hatchback '| 11th Gen      |[<&pencil>]|[<&delete>]|*    
  }
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }

}
@endsalt
