@startsalt
{
  <size:15><b>Model List |[<size:25><&x>]|*
  ==
  .
  {
      .|Code        |: |"               "|*
      .|Model Name  |: |"               "|*
      .|Remark      |: |"               "|.|.|[Filter <&magnifying-glass>]| [Clear <&x>]|*
  }
  .
  --
  {
  [Add New Model <&document>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|* 
  }
  --
  {#
    |<b>    Code |<b>          Model Name        |<b> Remark |<b> Action |*|*|*
    |'  GGN155   | Hilux                         | 8th Gen       |[<&pencil>]|[<&delete>]|*
    |'  TGN166   | Fortuner                      | 2nd Gen       |[<&pencil>]|[<&delete>]|*
    |'  ZRE172   | Corolla Altis                 | 11th Gen      |[<&pencil>]|[<&delete>]|*
    |'  MBZ173   | Yaris Gazoo Racing Hatchback '| 11th Gen      |[<&pencil>]|[<&delete>]|*    
  }
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }

}
@endsalt
