@startsalt
{
  <size:15><b>Model List |[<size:25><&x>]|*
  ==
  {
    .|Model Code        |: |"               "|*
    .|Model Name        |: |"               "|*
    .|Type              |: {(X)All      |()PxP     |   ()Lot  }*
    .|Remark            |: |"                      "|              |[Filter <&magnifying-glass>]| [Clear <&x>]|*
  }
  .
  --
  {
  [Add New Model <&document>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|* 
  }
  --
  {#
   | <b>No | <b>Model Code |                <b>Model Name                |  <b>Type  | <b># Parts |<b>     Remark     |<b> Action |*|*|*
  }
  No Data Found
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }

}
@endsalt
