@startsalt
{
  <size:15><b>Model - New |[<size:25><&x>]|*
  ==
  
  {   
    .|Model Code              |: |"        "|*
    .|Model Name              |: |"             "| *
    .|Destination             |: |"    "|[<&magnifying-glass>]|*
    .|.                       |: |*
    .|Implement. Period       |: |"    ."|*
    .|Remark                  |: |"                 "|*
  }
  .
--
  {
    [Add Part <&document>]|[Katashiki]|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|
  }
  --
  {#
    | <b>No |                                                                                                     <b>PART INFO                                                                                                                                  |*|*|*|*|*|*|*|*|*|*|*|<b>  Katashiki  |*|*     |  <b>Action  |*|*
    |.     |       <b>Part No       |                           <b>Name                           |     <b>Parent     | <b>Type | <b>Supplier ID |          <b>Supplier Name          |    <b>L  |   <b>W   |    <b>H   |  <b>Wt/pc  | <b>Qty |<b>   Total Wt                         | <b>AX | <b>AY | <b>AU |.|*|*
  }
  No Data Found
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
}

  @endsalt