@startsalt
{
  <size:15><b>Model List |[<size:25><&x>]|*
  ==
  {
    .|Model Code        |: |"               "|[<&magnifying-glass>]|*
    .|Model Name        |: |"               "|*
    .|Destination       |: |"            "|[<&magnifying-glass>]|*
    .|Implement. Period  |: |"    ."|*
    .
  }*
  {|                                                                                |[Search <&magnifying-glass>]|[Clear <&x>]|}
  --
  {
    [Add Model <&document>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|* 
  }
  --
  {#
    | <b>No | <b>Model Code |                <b>Model Name                 | <b>Dest Code |   <b>Dest Name   | <b># Parts |<b>        Remark        |<b> Action |*|*|*
    |    1  |     188D      | Hilux Edit                                   |    301B       | Argentina        |       26   | 8th Gen           |[<&pencil>]|[<&delete>]|*
  }
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }

}
@endsalt
