@startsalt
{
   <size:15><b>Inland Cost rates|[<size:25><&x>]|*
  ==
  {
    .|Period                          |:|^ 02.2025 ^|*
    .|Container Volume M3             |:|"   47.7  "|*
    .|40 feet container rent rate     |:|" 86.177  "|*
    .|20 feet container rent rate     |:|" 86.177  "|*
    .|Milkrun rate (per m3)           |:|" 60.577  "|*
    .|Milkrun efficiency rate   (%)   |:|"  64     "|*
  }
  --
  {
    [Save]|[Cancel]
  }
}|
@endsalt