@startsalt
{
<size:15><b>Parameters|[<size:25><&x>]|*
==
{/ Inland |<b>Labor Cost | Man Hour | History}*
  
  .
    {
    .|Period                           |:|^ 02.2025 ^|*
    .|Direct Labor Rate (DL)  Rp/Hour  |:|"  86.177"|*
    .|Indirect Labor Rate (IDL) Rp/M3  |:|"106.835" |*
    .|Facility Others Rate             |:|"  63.249"|*
  }
  --
  {
    [Save]|[Cancel]
  }






}
@endsalt