@startsalt
{+
  {
    .
    .|{
      {|Calc Code |:| "                                        "|}*
      --|--|*
      {                                                                |[ Save ]| [ Cancel ]|}*
    }
  }
}
@endsalt