@startsalt
{+
  |                                  |*
  |  <b><size:15>Generating Report   |*
  |.                                 |*
  |           　<size:45><&aperture> |*
  |         <b>       45%            |*
  |.                                 |*
  |{[Minimize]|     |[Cancel]}       |*
}
@endsalt