@startsalt
{+
  .|{
    <size:15><b>Supplier List |[<size:25><&x>]|*
    ==
    {
        .|Supplier Code  |: |"               "|*
        .|Supplier Name  |: |"               "|*
        .|Address        |: |"                         "|*      
        .|.              |. |"                         "|*                
    }
    .
    {
                                                                                           {|[Filter <&magnifying-glass>]| [Clear <&x>]|}*      
    }
    {
      !include ./components/supplier-action-buttons.puml
    }
    --
    {#
      !include ./components/supplier-tbl-header.puml
      |   1|      5062	       | MENARA TERUS MAKMUR		                  | Jl. Jababeka XI Blok H-3 No.12, Kawasan Industri Jababeka,...  |.          |.        |[<&pencil>]|[<&delete>]|*
      |   2|      722E	       | TOYOTA MOTOR THAILAND		                | 186 1 ถ. ทางรถไฟสายเก่าปากน้ำ Samrong Tai, Phra Pradaeng Dist... |.          |.        |[<&pencil>]|[<&delete>]|*
      |   3|      5453	       | VELASTO INDONESIA		                    | Kp. Nagrog RT04 / RW02 Desa Kertamukti, Kecamatan Campaka,...  |.          |.        |[<&pencil>]|[<&delete>]|*
      |   4|      5365	       | TOKAI RUBBER INDONESIA		                | Jl. Mitra Timur II Blok E No. 13-14, Parungmulya, Ciampel,...  |.          |.        |[<&pencil>]|[<&delete>]|*
      |   5|      5150	       | NAMICOH INDONESIA		                    | EJIP Industrial Park, Plot 6B-1, Cikarang Selatan, Bekasi,...  |.          |.        |[<&pencil>]|[<&delete>]|      
    }|
    --
    !include ../components/pagination.puml

    }
  }
@endsalt
