@startsalt
{+
  .|{
    <size:15><b>Supplier - New |[<size:25><&x>]|*
    ==
    {   
      |Supplier Code |: |" 50057 "|*
      |Supplier Name |: |" BINA SARI TANGGUH "| *
      |Address       |: |" Komp Industri Mekarmas Jl. Adurame  Blok J No 20 "|*
      |.             |. |" Bekasi Kota                                      "|*  
    } 
    .
    --
    {
    .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
    }
  }
}
@endsalt