@startsalt
{
  <size:15><b>Model - New
  ==
  .
  {   
    .|Code           |: |"        "|*
    .|Name           |: |"             "| *
    .|Generation     |: |"                 "|*
  }
  .
--  
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
}

  @endsalt