@startsalt
{
  <size:15><b>Module List
  ==
  .
  {
      .|Code    |: |"               "|*
      .|Type    |: |"                 "| [Search <&magnifying-glass>] |*      

  }
  .
  --
  [Add <&document>]
  --
  {#
    |<b>    Code |<b> Type Code '|<b>     Action |*|*|*
    |'  JJX45    | BX1B          |[<&pencil>]|[<&delete>]|[<&layers>]|*
    |'  AXB784   | BX2C          |[<&pencil>]|[<&delete>]|[<&layers>]|*
    |'  MMB844B '| BX3D          |[<&pencil>]|[<&delete>]|[<&layers>]|*
  }
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
