@startsalt
{
  <size:25>DPI List |[<size:25><&x>]|*
  ==
  {
      .|DPI No         |: |"                       "|           |.|.|CFC/Pjt |: |"               "|*|*
      .|Ref DPI No     |: |"                       "|           |.|.|Model   |: |"               "|*|*
      .|From           |: |"                       "|           |.|.|To      |: |"               "|*|*
      .|Issued Date    |: {|"21.06.2025"|'to'|"21.06.2025"|} |.|.|Status  |: | {.| ^Any^Draft^Submitted^Rejected^Approved^}|       .      |.| [Search] |   [Clear] |*    
      .|Effective Date |: {|"21.06.2025"|'to'|"21.06.2025"|}
  }
  .
  .
  {   
    {
      .|    [ Add DPI <&flash>]  |[Create PCI <&wrench>] |*
    }   
    .
    {
    --   
      {+
        {#
        |<b> DPI No. |<b> Ref DPI No. |<b> Issued Date  | <b>Effective Date |<b> CFC/Pjt    |<b> Model  |<b> # Parts |<b> # CPS |<b> From             |<b> To              |<b> Status     |<b> Action |*|*
        |D38403403   |A58503112       |23 Feb - 2025    | 01 Mar - 2025     |D54B          | D60B       |  2         |    1     |Andi Nuridwan       |.                  '|     Draft       | [<&pencil>]|[<&trash>]|* 
        }
      }
    }
  }
  --
  {
  << <  __1__  > >>  |'      3 <&chevron-bottom> per page |*
  }  
}
@endsalt
