@startsalt
{
  <size:15><b>Module Type New|[<size:25><&x>]|*
  ==
  .
  {   
    .|Type Code         |: |" T3A       "|*
    .|Item No           |: |" DX09TY        "| [Search] |* 
    .|E-Warehouse Price |: | 4.000.000          |*
    .|Dim  Outer (mm<sup>3</sup>) |: {L:|" 2250"|W:|" 40 "|H:|" 12 "|}|*
    .|Dim  Outer (m<sup>3</sup>)  |: 2,88|*
    .|Dim  Inner (mm<sup>3</sup>) |: {L:|"   "|W:|"   "|H:|"   "|}|*
    .|Dim  Inner (mm<sup>3</sup>) |: 2,37 |*
  }
  .
--  
  {
|Dest Code |: |^301B - Argentina ^ 807B - Indonesia ^ 537B - Afrika^|*
.
.   
|Price     |: |" 5.000.000 "|
}
--  
{
  .|  [Save <&data-transfer-download>] |  [Cancel <&circle-x>] |*
  }
}

  @endsalt