{
  .|Project Code       |: |" 286W       "|*
  .|Project Name       |: |" Engine Redesign "|*
  .|Project Manager    |: {|" Arif Fikri "|[<&people>]|}*
  .|Description        |: {SI|Complete redesign of the engine system 
                         for improved perfomance 
  .|}*
}