{
  .|Project Code       |: |"            "|*
  .|Project Name       |: |"                        "|*
  .|Project Manager    |: {|" Arif Fikri "|[<&people>]|}*
  .|Description        |: {SI|"                                "
  .
  .|}*
}