@startuml
@startsalt
{
  <b><size:20>CPS - New |[<size:25><&x>]|*
  ==
  {
    {
      <b>CPS No.      |: {| D38403403 |}
      <b>Ref CPS No.  |: {| A58503112 |}| *
      Issue  Date     |: {|  23 Feb - 2025  |}
      Effective Date  |: {|  01 Mar - 2025  |}
      .
      DPI No.         |: {|            |}| *
      CFC/PJT         |: {| CF2025020001 |}
      Export Dest     |: | Thailand |*
      Model           |: {| DX01UB |}
      Part No         |: {| 25051BZ260-00 |}
    }
    --
    {
      .|.|Part Name   |: |CONVERTER SUB-ASSY, EXHAUST MANIFOLD                    |*
      .|.|Supplier    |: |FUTABA INDONESIA|*
      .|.|Plant Code  |: | AI01|*
      .|.|Dock Code   |: | AI-D-001|*

    }
    --
    {*
      <b><size:14> <&chevron-bottom> Images
    }
    {#
      |<b>Part        :|{ 
        <b>Caption: 
        "                       "
        "                       "
        "                       "
      }|<size:80><&wrench>|<size:30><b>+|*
    }
    --
    {#
      |<b>Packing : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&box>|<size:80><&box>|<size:80><&box>|<size:80><&box>|<size:80><&box>|<size:30><b>+|*
    }
    --
    {#
      |<b>Outer    : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:30><b>+|*
    }
    {#
      |<b>QKP      : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:30><b>+|*
    }
    {#
      |<b>BKP      : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&image>||<size:80><&image>|<size:30><b>+|*
    }
    --
    {*
      <b><size:14> <&chevron-bottom> Packing
    }
    --
    {
      '1490	1125	730
      <b>OUTER
      { Module Type     |: |"  58   " | [<&magnifying-glass>] | }*  
      {
        .| Dimension     |: | 1490 | x | 1125 | x | 730 | cm <sup>3</sup> |*
        .| Inner         |: | 1,23 | m<sup>3</sup>                      |*
        .| Outer         |: | 1,23 | m<sup>3</sup>                      |*
      }
    }
    --
    {
      |<b>INNER   | [<size:10>add <&plus>] |*
    }
    {#
      |<b> Pack Material No     |<b> Suffix |<b> Name         |<b>Item Type |<b> Parent    |<b> Supplier ID |<b> Supplier Name |<b> L  |<b> W  |<b> H  |<b> Wt/pc |<b> Qty |<b> Total Wt  |<b> Action|*|*
      | AB12CD34EF             | 00        | Outer Box        | EE-122LX    |             .| TMMIN          | TMMIN             |360    |550    |240    |         .| 1      |           . |[<&pencil>]|[<&trash>]|*
      | GH56IJ78KL             | 00        | Carton Sheet     | FF-FTB      |             .| TMMIN          | TMMIN             |.      |.      |.      |         .| 1      |           . |[<&pencil>]|[<&trash>]|*
      | MN90OP12QR             | 00        | Plastic Sheet   '| DD-5G       |             .| TMMIN          | TMMIN             |.      |.      |.      |         .| 1      |           . |[<&pencil>]|[<&trash>]|*
      | ST34UV56WX             | 00        | Anti Rust        | AA622F      |             .| TMMIN          | TMMIN             |.      |.      |.      |         .| 2      |           . |[<&pencil>]|[<&trash>]|*
    }
    --
    Note :
    {SI
      Menggunakan Anti Rust 2 lapis 
      Plastic sheet dipastikan ketebalan 2 mm dan ada bubblenya 
      .
      .
    }
  }
  {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
  .
  .
  <b>List of Notes:
  --
  <i>No Data Found 
}
@endsalt
@enduml
