@startuml
@startsalt
{
  <b><size:20>CPS - New |[<size:25><&x>]|*
  ==
  {
    {
      CPS No.         |:{|CPS 301B DB01UB 25051BZ26000|}
      Ref CPS No.     |:{|                   |}| *      
      CFC Model       |:{|DX01UB      |}
    }
    {
      |     |Destination     |:| 301B - Thailand |*
      |     |Project Code    |:| 118D |*
    }
    {
      Part No         |:{|25051BZ260-00 | [<&spreadsheet>]}
    }
    {
      |     Part Name       |: | CONVERTER SUB-ASSY, EXHAUST MANIFOLD        |*
      |     Supplier        |: | 5008 - KOMPONEN FUTABA       |*
    }
    --
    {*
      <b><size:14> <&chevron-right>Logistic Information
    }
    --
    {*
      <b><size:14> <&chevron-right> PSE Info
    }
    --
    {*
      <b><size:14> <&chevron-bottom> Images
    }
    {#
      |<b>Part        :|{ 
        <b>Caption: 
        "                       "
        "                       "
        "                       "
      }|<size:80><&wrench>|<size:30><b>+|*
    }
    --
    {#
      |<b>Packing : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&box>|<size:80><&box>|<size:80><&box>|<size:80><&box>|<size:80><&box>|<size:30><b>+|*
    }
    --
    {#
      |<b>Outer    : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:30><b>+|*
    }
    {#
      |<b>QKP      : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:80><&image>|<size:30><b>+|*
    }
    {#
      |<b>BKP      : |{ 
        <b>Caption: 
        "                        "
        "                        "
        "                        "
      }|<size:80><&image>||<size:80><&image>|<size:30><b>+|*
    }
    --
    {*
      <b><size:14> <&chevron-bottom> Packing
    }
    --
    {
      |Part Weight      |: |"     "|*
      |Packing Weight   |: |"     "|*
      |Packing Qty      |: |"      "|*
      |Pcs/Kanban       |: |"     "|*
      }
      .
      '1490	1125	730
      <b>OUTER
      --
      {|Module |(X)|      |Mesh Pallet|()|}*
      --
      {
        {      Module Type     |: |"T1B TAR " | [<&magnifying-glass>] | }*  
          {
            .|       Dimension     |: | 80 | x | 60 | x | 50 | cm <sup>3</sup> |*
            .|       Inner         |: | 1,50 | m<sup>3</sup>                      |*
            .|       Outer         |: | 1,55 | m<sup>3</sup>                      |*
          }
      }      
    }    
    --
    {
      |<b>INNER   | [<size:10>add <&plus>] |*
    }
    {#
      | <b>No |     <b>Material No     | <b>Suffix |                   <b>Material Name                   |   <b>ItemNo  |   <b>Parent Mat     | <b>Supplier ID  |     <b>Procure |                   <b>Supplier Name                   | <b>L   | <b>W  | <b>H | <b>wt/pc | <b>Qty | <b>Total Wt |<b>Time (sec)| <b>Action |*
      |   1   | AB12CD34EF             |   00      | Outer Box                                            | EE-122LX     |                    .| TMMIN           | ^ Supplier^    | TMMIN                                                 | 360    | 550   | 240  |         .| "  1"  |           . | "    20"    |[<&pencil>]|[<&trash>]|*
      |   2   | GH56IJ78KL             |   00      | Carton Sheet                                         | FF-FTB       |                    .| TMMIN           | ^  TMMIN  ^    | TMMIN                                                 |.       |.      |.     |         .| "  1"  |           . | "  180 "    |[<&pencil>]|[<&trash>]|*
      |   3   | MN90OP12QR             |   00      | Plastic Sheet   '                                    | DD-5G        |                    .| TMMIN           | ^ Supplier^    | TMMIN                                                 |.       |.      |.     |         .| "  1"  |           . | "    50"    |[<&pencil>]|[<&trash>]|*
      |   4   | ST34UV56WX             |   00      | Anti Rust                                            | AA622F       |                    .| TMMIN           | ^  TMMIN  ^    | TMMIN                                                 |.       |.      |.     |         .| "  2"  |           . | "    60"    |[<&pencil>]|[<&trash>]|*    
    }
    --
    Note :
    {SI
      Menggunakan Anti Rust 2 lapis 
      Plastic sheet dipastikan ketebalan 2 mm dan ada bubblenya 
      .
      .
    }
  }
  {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
  .
  .
  <b>List of Notes:
  --
  <i>No Data Found 
}
@endsalt
@enduml
