
 |Item No         |: |" B0212275-14  "|[Search eWH <&flash>]|*
 |Material Name   |: |" 3I-A                       "|*
 |Price           |: |" 2.360  "|*
 |Material Type   |: | { ^Inner^Outer^Module^ } |*
 .  
 .
 
 |Supplier Code    |:{|"          "|[<&magnifying-glass>]|} *
  {
    |    Supplier Name   |: | |*
    |    Address         |: | |*
    |    Plant Code      |: | |*
  }*

 |E-Warehouse       | *
    |    Item No   |: |" B0212275-14  "|*
    |    Price     |: |" 2.100  "|*
 |Dimension|*
    |    Length (mm)   |: |"  200"|            |Weight/pc (gr)    |: |"  260 "|*
    |    Width (mm)    |: |"  120"|            |Qty/Box           |: |"     2"|*
    |    Height (mm)   |: |"  100"|            |Total Weight (gr) |: |"  520 "|*

