  1| B021-227514     | 3I-A               |      2.500             | 1X0923 |           2.360    |       Inner |[<&pencil>]|[<&delete>]|*
  2| B021-471022     | DD-5G1-A           |      3.220             | MX09AB |           3.146    |       Inner |[<&pencil>]|[<&delete>]|*
  3| B028-012214     | FF-2A              |      1.067             | 2B0912 |           1.067    |       Inner |[<&pencil>]|[<&delete>]|*
  4| R/Rack T3A TASA | T3A                |    38.250              | 2X49MM |         38.162     |       Outer |[<&pencil>]|[<&delete>]|*
  5| B752-991020     | Bolt               |  190.000               | 3X19TY |       192.000      |       Outer |[<&pencil>]|[<&delete>]|*