@startuml
@startsalt
{+
  .|{
    {<b><size:20>CPS - New |                                                                                                                                                                                                                                              |[<size:15> Download <&data-transfer-download>]}|[<size:25><&x>]|*
    ==
    {
    !include ../components/form-header-filled.puml
    --
    !include ../components/logistic-section-collapsed.puml
    --
    !include ../components/pse-section-filled-expanded-rw.puml
    --
    !include ../components/images-section-collapsed.puml
    --
    !include ../components/packing-section-collapsed.puml
    --
    Note :
    {SI
      "                                          "
      .
      .
      .
    }
    }
    {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
    .
    .
    <b>List of Notes:
    --
    <i>No Data Found       
  
    }
  }
}
@endsalt
@enduml
