@startsalt
{+
  .|{
    <size:25>DPI List |[<size:25><&x>]|*
    ==  

    !include dpi-search-header.puml
    --
    [Download DPI]
    --
    {#
      !include dpi-tbl-header.puml
    }
    {
      No Data Found    
    }
    --
    !include ./components/pagination.puml
  }
}
@@endsalt