@startsalt
{
  <size:15><b>CFC/Pjt - New|[<size:25><&x>]|*
  ==
  .
  {
    .|CFC/PJT Code       |: |"            "|*
    .|CFC/PJT Name       |: |"                        "|*
    .|CFC/PJT Type       |: |{| ^PxP^Lot^ }|* 
    .
    .|Description        |: |"                                               "|*
    .|Project Manager    |: {|"           "|[<&people>]|}*
    .|Start Date         |: |"  YYYY-MM-DD  "|[<&calendar>]|*
    .|End Date           |: |"  YYYY-MM-DD  "|[<&calendar>]|*
    .|Status             |: |{| ^Draft^Active^On Hold^Completed^ }|*
    .
    .
    .
    .|Note               |: {SI|"                                "
    .
    .|}*
  }
  .
  --
  {
    [Add Model <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    |<b> No |<b> Model Code |<b> Model Name     |<b> Remark |<b> Action |*  
  }
  No Data Found
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
==
}
@endsalt