@startsalt
{
  <size:15><b>Project List|[<size:25><&x>]|*
  ==
  {
    .|Project Code      |: {|"          "|[<&magnifying-glass>]|}*
    .|Project Name      |: |"                        "|*    
    .|Related Models    |: {|"          "| [<&magnifying-glass>]|}*
    .|Project Manager |: {|"              "|[<&people>]|}*
  }
  {|                                                                                              |[Filter <&magnifying-glass>]|[Clear <&x>]|}
  --
  {
  [New CFC/PJT <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>Project Code |        <b>Project Name         | <b>Project Manager |          <b>Models          |<b>     Action      |*|*|*
    |       286W      | Engine Redesign                | Arif Fikri         | GGN155, TGN166              |[<&pencil>]|[<&layers>]|[<&trash>]|*
  }
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
