@startsalt
{
  <size:15><b>ProCFC/Pjt - New|[<size:25><&x>]|*
  ==
  .
  {
    .|CFC/PJT Code       |: |"286W      "|*
    .|CFC/PJT Name       |: |"Engine Redesign         "|*
    .|CFC/PJT Type       |: |{| ^PxP^Lot^ }|* 
    .
    .|Description        |: |"Complete redesign of the engine system for improved performance"|*
    .|Project Manager    |: {|"Arif Fikri"|[ <&people>]|}*
    .|Start Date         |: |"  2025-01-01  "|[<&calendar>]|*
    .|End Date           |: |"  2025-06-30  "|[<&calendar>]|*
    .|Status             |: |{| ^Draft^Active^On Hold^Completed^ }|*
    .
    .
    .
    .|Note               |: {SI|"                                "
    .
    .|}*
  }
  .
  --
  {
    [Add Model <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    |<b> No |<b> Model Code |<b> Model Name     |<b> Remark |<b> Action |*|*|*|*
  }
  No Data Found
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
==
}
@endsalt