@startsalt
{
  <size:15><b>Project - New|[<size:25><&x>]|*
  ==
  {
    .|Project Code       |: |" 286W       "|*
    .|Project Name       |: |" Engine Redesign "|*
    .|Project Manager    |: {|" Arif Fikri "|[<&people>]|}*
    .|Description        |: {SI|Complete redesign of the engine system 
                           for improved perfomance 
    .|}*
  }
  .
  --
  {
    [Add Model <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>No | <b>Model Code |     <b>Model Name     |           <b>Remark           |<b> Action |*
    |    1  |    694W     | Innova Gasoline       | 1st Gen                       | [<&trash>]|*
    |    2  |    758W     | Fortuner Diesel       | 2nd Gen                       | [<&trash>]|*
  }
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
}
@endsalt