@startsalt
{
  <size:15><b>Project - New|[<size:25><&x>]|*
  ==
  {
    .|Project Code       |: |"            "|*
    .|Project Name       |: |"                        "|*
    .|Project Manager    |: {|" Arif Fikri "|[<&people>]|}*
    .|Description        |: {SI|"                                "
    .
    .|}*
  }
  .
  --
  {
    [Add Model <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>No | <b>Model Code |     <b>Model Name     |           <b>Remark           |<b> Action |*
    |    1  |    GGN155     | Innova Gasoline       | 1st Gen                       | [<&trash>]|*
    |    2  |    TGN166     | Fortuner Diesel       | 2nd Gen                       | [<&trash>]|*
  }
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
}
@endsalt