@startsalt
{
  <size:15><b>CFC/Pjt List|[<size:25><&x>]|*
  ==
  {
    .|CFC/PJT Code      |: {|"          "|[<&magnifying-glass>]|}*
    .|CFC/PJT Name      |: |"                        "|*    
    .|Related Models    |: {|"          "| [<&magnifying-glass>]|}*
    .|SOP Packing        |: {"  .  "| | <size:8><i>cth: 02.2025* }
    .|Status |:|
    {
      [X] All
      [] Draft
      [] Active
      [] On Hold
      [] Completed
    }|*
    .|Project Manager |: {|"              "|[<&people>]|.|.|.|.||[Filter <&magnifying-glass>]}|[Clear <&x>]
  }
  .
  --
  {
  [New CFC/PJT <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>CFC/PJT Code |        <b>CFC/PJT Name         | <b>Project Manager | <b>SOP Packing | <b>Status      |          <b>Models          |<b>     Action      |*|*|*
  }
  No Data Found
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
