@startsalt
{
  <size:15><b>Project List | [<size:25><&x>]|*
  ==
  {
    .|Project Code      |: {|"       "|[<&magnifying-glass>]|}*
    .|Project Name      |: |"                        "|*
    .|Type              |: |{| ^All^PxP^Lot^ }|*
    .|Related Models    |: |"GGN155, TGN166"| [<&magnifying-glass>]|*
    .|Status |:|
    {
      [ ] All
      [x] Draft
      [x] Active
      [ ] On Hold
      [ ] Completed
    }|*
    .|Project Manager |: |"              "|[<&people>]|*
  }
  [Filter <&magnifying-glass>]|
  .
  --
  {
  [New Project <&plus>]||.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    |<b> Project Code    |<b> Project Name          |<b>Type|<b> Manager         |<b> Start Date |<b> End Date   |<b> Status     |<b>      Models     |<b>    Action |*|*|*|*|*|*|*
    |' PRJ001            | Engine Redesign          |PxP    | Arif Fikri         | 2025-01-01    | 2025-06-30    | Draft         | GGN155, TGN166     |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ002            | Suspension Optimization  |PxP    | Khedi Rachman      | 2025-02-15    | 2025-07-15    | Active        | AGX210             |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ003            | EV Interior Upgrade      |Lot    | Toni Saputra       | 2024-11-10    | 2025-03-20    | Completed     | GRX130, ZYX110     |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ004            | Smart Dashboard Testing  |PxP    | Dono Wijaya        | 2025-03-01    | 2025-10-01    | On Hold       | GRS182             |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ005            | New Engine Assembly Line |Lot    | Ridwan Maulana     | 2025-04-05    | 2025-09-30    | Active        | TGN166             |[<&pencil>]|[<&layers>]|[<&trash>]|*
  }
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
