@startsalt
{
  <size:15><b>Project List|[<size:25><&x>]|*
  ==
  {
    .|Project Code      |: {|"          "|[<&magnifying-glass>]|}*
    .|Project Name      |: |"                        "|*    
    .|Related Models    |: {|"          "| [<&magnifying-glass>]|}*
    .|Project Manager |: {|"              "|[<&people>]|}*
  }
  {|                                                                                              |[Filter <&magnifying-glass>]|[Clear <&x>]|}
  --
  {
    [Add Project <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>No | <b>Project Code |        <b>Project Name         | <b>Project Manager |          <b>Models          |<b>     Action      |*|*|*
    |   1 |     286W          | Engine Redesign                | Arif Fikri           | GGN155, TGN166             |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |   2 |     332W          | Suspension Optimization        | Khedi Rachman        | AGX210                     |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |   3 |     385W          | EV Interior Upgrade            | Toni Saputra         | GRX130, ZYX110             |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |   4 |     388W          | Smart Dashboard Testing        | Dono Wijaya          | GRS182                     |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |   5 |     408W          | New Engine Assembly Line       | Ridwan Maulana       | TGN166                     |[<&pencil>]|[<&layers>]|[<&trash>]|*
  }        
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
