@startsalt
{
  <size:15><b>CFC/Pjt List | [<size:25><&x>]|*
  ==
  {
    .|CFC/PJT Code      |: {|"          "|[<&magnifying-glass>]|}*
    .|CFC/PJT Name      |: |"                        "|*    
    .|Related Models    |: {|"          "| [<&magnifying-glass>]|}*
    .|Type              |: {|{(X)All}   '|    {()PxP}        '|   ()Lot}
    .|Start Date        |: {"          "|[<&calendar>] |'  -  '| "          "|[<&calendar>]  }*
    .|End Date          |: {"          "|[<&calendar>] |'  -  '| "          "|[<&calendar>]  }*
    .|Status |:|
    {
      [X] All
      [] Draft
      [] Active
      [] On Hold
      [] Completed
    }|*
    .|Project Manager |: {|"              "|[<&people>]|.|.|.|.||[Filter <&magnifying-glass>]}|[Clear <&x>]
  }
  .
  --
  {
  [New CFC/PJT <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    |<b> CFC/PJT Code |<b> CFC/PJT Name          |<b>Type|<b> Manager         |<b> Start Date |<b> End Date   |<b> Status     |<b>      Models     |<b>    Action |*|*|*|*|*|*|*
    |' PRJ001            | Engine Redesign          |PxP    | Arif Fikri         | 2025-01-01    | 2025-06-30    | Draft         | GGN155, TGN166     |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ002            | Suspension Optimization  |PxP    | Khedi Rachman      | 2025-02-15    | 2025-07-15    | Active        | AGX210             |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ003            | EV Interior Upgrade      |Lot    | Toni Saputra       | 2024-11-10    | 2025-03-20    | Completed     | GRX130, ZYX110     |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ004            | Smart Dashboard Testing  |PxP    | Dono Wijaya        | 2025-03-01    | 2025-10-01    | On Hold       | GRS182             |[<&pencil>]|[<&layers>]|[<&trash>]|*
    |' PRJ005            | New Engine Assembly Line |Lot    | Ridwan Maulana     | 2025-04-05    | 2025-09-30    | Active        | TGN166             |[<&pencil>]|[<&layers>]|[<&trash>]|*
  }
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
