@startsalt
{
  <size:15><b>ProCFC/Pjt - New|[<size:25><&x>]|*
  ==
  {
    .|CFC/PJT Code       |: |" 286W           "|*
    .|CFC/PJT Name       |: |" Engine Redesign        "|*
    .|SOP Packing        |: {"02.2025  "| | <size:8><i>cth: 02.2025* }
    .|Status             |: |{| ^Draft^Active^On Hold^Completed^ }|*
    .
    .
    .
    .|Project Manager    |: {|" Arif Fikri "|[<&people>]|}*
    .|Description        |: |"                                   "|*
    .|Note               |: {SI|"                                "
    .
    .|}*
  }
  .
  --
  {
    [Add Model <&plus>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>No | <b>Model Code |     <b>Model Name     |           <b>Remark           |<b>     Action     |*|*|*
  }
  No Data Found
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
==
}
@endsalt