@startsalt
{
  <size:15><b>Project List|[<size:25><&x>]|*
  ==
  {
    .|Project Code      |: {|"          "|[<&magnifying-glass>]|}*
    .|Project Name      |: |"                        "|*    
    .|Related Models    |: {|"          "| [<&magnifying-glass>]|}*
    .|Type              |: {|{(X)All}   '|    {()PxP}        '|   ()Lot}
    .|Status |:|
    {
      [ ] All
      [X] Draft
      [X] Active
      [ ] On Hold
      [ ] Completed
    }|*
    .|Project Manager |: |"              "|[<&magnifying-glass>]|*
  }
  [Filter <&magnifying-glass>]|
  .
  --
  {
  [New Project <&plus>]||.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    |<b> Project Code    |<b> Project Name          |<b> Type '|<b> Manager         |<b> Start Date |<b> End Date   |<b> Status     |<b>Models     |<b>Action |*|*|*|*|*|*|*
  }
  No Data Found
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
