@startsalt
{
  <size:15><b>Project - New
  ==
  .
  {
    .|Project Code       |: |"PRJ001      "|*
    .|Project Name       |: |"Engine Redesign         "|*
    .|Description        |: |"Complete redesign of the engine system for improved performance"|*
    .|Project Manager    |: |"Arif Fikri"|[Search <&magnifying-glass>]|*
    .|Start Date         |: |"  2025-01-01  "|[<&calendar>]|*
    .|End Date           |: |"  2025-06-30  "|[<&calendar>]|*
    .|Status             |: |{| ^Draft^Active^On Hold^Completed^ }|*
    .|Note               |: {SI|"                                "
    .
    .|}*
  }
  .
  --
  {
    [Add Model <&plus>]|*
  }
  {#
    |<b> No |<b> Model Code |<b> Model Name     |<b> Generation |<b> Action |*|*|*|*
    | 1     | GGN155        | Innova Gasoline   | 1st Gen       | [<&trash>]|*
    | 2     | TGN166        | Fortuner Diesel   | 2nd Gen       | [<&trash>]|*
  }
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
==
}
@endsalt