@startsalt
{+
  .|{
    <size:25><b>Packing Cost Calculation New|[<size:25><&x>]|*
    ==
    !include ./headers/_generic.puml
    --
    [<color:#9a9a9a>Download]
    --
    {#
      !include calc_tbl_header.puml
    }
    No Data Found
    
    !include ./components/pagination.puml
  }
 }
@endsalt