@startsalt
{
  <size:15><b>Material List | [<size:25><&x>]|*
  ==
  {
    .|Material No      |: |"           "|[<&magnifying-glass>]|*
    .|Material Name    |: |"           "|*
    .|Parent Material  |: |"           "|[<&magnifying-glass>]|*
    .|Item No          |: |"           "|[<&magnifying-glass>]|*
    .|Price            |: |"           "|[<&magnifying-glass>]|*
    .|Material Type    |: | { ^Inner^Outer^Module^ } |*  
    .
  }
    {|                                                                                           |[Search <&magnifying-glass>]|[Clear <&x>]|}
  
  --
  {
  [Add Material <&document>] |.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>No  |  <b>Material No | <b> Material Name  |  <b>Parent Material  |  <b> Item No     | <b> Price  | <b> Material Type  |<b> Action |*|*|*|*|*|*|*
  }
  No Data Found
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }  
}
@endsalt
