@startsalt
{
  <size:15><b>Material List | [<size:25><&x>]|*
  ==
  {
    .|Material No      |: |"           "|[<&magnifying-glass>]|*
    .|Material Name    |: |"           "|*
    .|Parent Material  |: |"           "| [<&magnifying-glass>]|*
    .|Item No      |: |. |*
    .|Price            |: |"           "|[<&magnifying-glass>]|*
    .|Material Type    |: | { ^Inner^Outer^Module^ } |*  
    .
  }
    {|                                                                                           |[Search <&magnifying-glass>]|[Clear <&x>]|}
  --
  {

  }
  {
  .
  }
  --
  {
  [Add Material <&document>] |.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
    | <b>No  |  <b>Material No  | <b> Material Name  |  <b>Parent Material  | <b> Item No | <b> Price  | <b> Material Type  |<b> Action |*|*|*|*|*|*|*
   .1        | B021-227514      | 3I-A               |                      | DX09TY      |     2.360      |  Inner             |[<&pencil>]|[<&delete>]|*
   .2        | B021-471022      | DD-5G1-A           |                      | DX09TY      |     3.146      |  Inner             |[<&pencil>]|[<&delete>]|*
   .3        | B028-012214      | FF-2A              |                      | DX09TY      |     1.067      |  Inner             |[<&pencil>]|[<&delete>]|*
   .4        | R/Rack T3A TASA  | T3A                |                      | DX09TY      |   38.162      |  Outer             |[<&pencil>]|[<&delete>]|*
   .5        | B752-991020      | Bolt               |                      | DX09TY      |  192.000      |  Outer             |[<&pencil>]|[<&delete>]|*
  }
  
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }  
}
@endsalt
