{
  Model         |: {|^    All^|[<&magnifying-glass>]|}*
  Impl. Period  |: {|^    All^|[<&magnifying-glass>]|}*
  Destination   |: {|^    All^|[<&magnifying-glass>]|}*
  Part          |: {|^    All^|[<&magnifying-glass>]|}*  
  .|.|.|.|                                              {[Calculate <&magnifying-glass>] | [Clear <&x>]}
}