@startuml
@startsalt
{
  <b><size:20>ECI - New |[<size:25><&x>]|*
  ==
  {
    {
      ECI No.      |:{|"PSI 301B DB01UB 25051BZ26000"|}
      Ref CPS No.  |:{|"CPS 301B DB01UB 25051BZ26000"| [<&magnifying-glass>]}| *
      Impl. Period |:|"04.07"|*
      CFC Model       |:{|DX01UB      |}
    }
    {
      |     |Destination     |:| 301B - Thailand |*
      |     |Project Code    |:| 118D |*
    }
    {
      Part No         |:{|"25051BZ260-00"| [<&spreadsheet>]}
    }
    {
      |     Part Name       |: | CONVERTER SUB-ASSY, EXHAUST MANIFOLD        |*
      |     Supplier        |: | 5008 - KOMPONEN FUTABA       |*
    }
    --
    !include ./components/logistic-section-collapsed.puml
    --
    !include ./components/pse-section-expanded-rw.puml
    --
    !include ./components/cps-images-section-expanded-ro.puml
    --
    !include ./components/packing-section-expanded-rw.puml
    --
    !include ./components/inner-tbl-rw.puml
    --
    Note :
    {SI
      "                                          "
      .
      .
      .
    }
    .
    {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
    .
    .
    <b>List of Notes:
    --
    <i>No Data Found 
  }
}
@endsalt
@enduml
