@@startsalt
{
  ==
  {  
   |<b>Date   |:|20 Feb 2025 13:10  |*
   |<b>From   |:|Jonathan Hairi     |*
   |<b>Dept   |:|PPMD               |*
  }
  ---
  {}
    Harus diganti Qty menjadi 2 
    Agar lebih aman ketika dikirim ke supplier lain
    dan diganti Material No nya dengan Mat No : #12312312 00
    dari supplier Materindo Indigo
  }
}
@@endsalt