@startsalt
{
  <size:25><b>Packing Cost Calculation List|[<size:25><&x>]|*
  ==
  {
    .|Pack Cost Cal Code  |: {|"          "|[<&magnifying-glass>]|}*
    .|Period              |: |^All^|*    
    .|Dest Code           |: {|^All^| }*
      .|.|.|{
      .| |' -  '|  | *
      }
    .|Model Code        |: {"          "|[<&magnifying-glass>]|}*
    .|Type              |: {|{(X)All}   '|    {()PxP}        '|   ()Lot} |*
    .|.|.|.|.|                                              {[Filter <&magnifying-glass>] | [Clear <&x>]}
  }
  --
  {
    | [Calculate Packing Cost] |.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|* 
  }
  --
  {#
    |<b>No  |       <b>PPR Code     |   <b>Status  |<b>   Period   |<b> Dest Code |<b> Dest Country |<b> Model  Code |<b> # Parts | <b>Type |<b> Action |*
  /'| 01    | 024J-301B-TASA-PXP  | Outdated     |02.2025        |  301B        |Argentina        |    024W        ||    120     | PxP     |  '/
  }
  No Data Found
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@@endsalt