|<b> <&chevron-right> |122810Y110   | 00       |HANGER, ENGINE, NO.1	               |            .       |5307-1          | SETIA GUNA SEJATI                    | 1200 | 350  | 300  | 0.8  |      10.200       | 10000       | 3%    | 10200       | 10000       | 3%    | 10200         | 10000       |     3%| 10200         | 10000       | 3%    |         10200 | 10000       | 3%    | 10200         | 10000       |     3%|*
|<b> <&chevron-right> |130500Y020   | 00       |GEAR ASSY, CAMSHAFT TIMING	         |            .       |5022-5          | DENSO INDONESIA CORPORATION (FAJAR)  | 1300 | 200  | 300  | 1.8  |               5   | 9000        | 3%    | 10200       | 10000       | 3%    | 10200         | 10000       |     3%| 10200         | 10000       | 3%    |         10200 | 10000       | 3%    | 10200         | 10000       |     3%|*
|<b> <&chevron-right> |25051BZ150   | 00       |CONVERTER SUB-ASSY, EXHAUST MANIFOLD |            .       |5376-1          | FUTABA INDONESIA                     |  100 | 100  | 300  | 1.2  |               5   | 13000       | 3%    | 10200       | 10000       | 3%    | 10200         | 10000       |     3%| 10200         | 10000       | 3%    |         10200 | 10000       | 3%    | 10200         | 10000       |     3%|*
|<b> <&chevron-right> |25051BZ260   | 00       |CONVERTER SUB-ASSY, EXHAUST MANIFOLD |            .       |5376-1          | FUTABA INDONESIA                     |  600 |   40 | 300  | 0.9  |             12    | 15000       | 3%    | 10200       | 10000       | 3%    | 10200         | 10000       |     3%| 10200         | 10000       | 3%    |         10200 | 10000       | 3%    | 10200         | 10000       |     3%|*  