/.
When duplicate button invoke in the table row, a new row will appear below it
and the CPS No will still be empty because the data hasn't been saved yet,
the Create CPS and Create PSI button will be hidden and Save and Cancel button 
will now appear under the table.
User can whether edit the new duplicated CPS, save it or delete it right away
if user choose to edit it, it will then open edit CPS form.
if user choose to save it, then the CPS No will still be empty but the status will be Draft
if user choose to delete it, then the save/cancel button will dissapear
and the create CPS and Create PSI button will reappear.
./
@startsalt
{
  <size:25>CPS List |[<size:25><&x>]|*
  ==
  {
    .|CPS No              |: {|"                   "|[<&magnifying-glass>] |}.|.|Ref CPS No          |: |"                   "|[<&magnifying-glass>]|*
    .|CFC/Model           |: {|"                   "|[<&magnifying-glass>] |}.|.|Project Code        |: |"                   "|[<&magnifying-glass>]|*
    .|Destination         |: {|^301B ^|    TAR - Argentina |}                .|.|CPS/PSI/ECI         |: {|^ CPS ^             |}*
    .|<b>Part          |: |*
    .|   Part No             |: {|"                 "|[<&magnifying-glass>]|}*
    .|   Supplier Code       |: {|                  |}*    
    .
    .|<b>Assignment          |: |*
    .|   From                |: {|"                   "|[<&people>]           |}.|.|To                  |: |"                   "|[<&people>]|*    
    .|   Impl. Time          |: |^02.2025^     |.|.|Status        |: {| ^Any^ |}*    
  }
  .
  {|                                                                                                                                                                                                                             |[Filter <&magnifying-glass>]|[Clear <&x>]|}
        {[Create CPS] | [Create PSI]|[Create ECI]|.|[Compare CPS]|.           |                        [Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|} *
    --
    {+
      {#
        '|<b> CPS No. |<b> Ref CPS No. |<b>DPI No|<b> Issued Date|<b>Effective Date|<b> CFC/Pjt   |<b> Model  |<b> # Parts        |<b> From               |<b> To                 |<b> Status       |<b>  Action   |*|*|*
        |  <b>No  |             <b>CPS/PCI/ECI No.              | <b>CPS/PCI/ECI |                 <b>Ref CPS No.                 | <b>Impl. Time | <b>Project Code |   <b>Model   |        <b>Destination        |      <b> Part No      |          <b>From          |           <b>To           |     <b>Status     |   <b>Submit Date   |    <b>Action    |*|*
        |    1   | CPS301B025J111150Y03000                    |       CPS      | CPS811C025J111150Y03000                        |   02.2025     |      835W       |    025J      |   301B TAR Argentina           | 111150Y03000          | Khedi Asmoro (PSE)        |  Cecep Gunadi (Aisin)     |    Submitted      |   06 Oct 2025     |[<&layers>]|[<&trash>]|*
        |    2   |.                                           |       CPS      | CPS811C025J111150Y03000                        |   02.2025     |      835W       |    025J      |   301B TAR Argentina           | 111150Y03000          | Khedi Asmoro (PSE)        |.                          |       Draft       |.                  |.          |[<&trash>]|*
      
    }

  }
  --
  {[Save] | [Cancel]|}*
  --
  {
  << <  __1__  > >>  |'      3 <&chevron-bottom> per page |*
  }  
}
@endsalt
