@startuml
@startsalt
{
  <b><size:20>CPS - New |[<size:25><&x>]|*
  ==
  {
    {
      CPS No.      |:{|"CPS 301B DB01UB 25051BZ26000"|}
      Ref CPS No.  |:{|"                 "| [<&magnifying-glass>]}| *      
      CFC Model       |:{|"DX01UB      "| [<&magnifying-glass>]}
    }
    {
      |     |Destination     |:| 301B - Thailand |*
      |     |Project Code    |:| 118D |*
    }
    {
      Part No         |:{|"25051BZ260-00"| [<&magnifying-glass>] | [<&spreadsheet>]}
    }
    {
      |     Part Name       |: | CONVERTER SUB-ASSY, EXHAUST MANIFOLD        |*
      |     Supplier        |: | 5008 - KOMPONEN FUTABA       |*
    }
    --
    {*
      <b><size:14> <&chevron-right>Logistic Information
    }
    --
    {*
      <b><size:14> <&chevron-right>PSE Information
    }
    --
    {*
      <b><size:14> <&chevron-right>Images
    }
    --
    {*
      <b><size:14> <&chevron-bottom> Packing
    }
    --
    {
      <b>OUTER
      --
      {|Module |(X)|      |Mesh Pallet|()|}*
      --
      {
        {      Module Type     |: |"      " | [<&magnifying-glass>] | }*  
          {
            .|       Dimension     |: | 00 | x | 00 | x | 00 | cm <sup>3</sup> |*
            .|       Inner         |: | 00 | m<sup>3</sup>                      |*
            .|       Outer         |: | 00 | m<sup>3</sup>                      |*
          }
      }
    }
    --
    {
      |<b>INNER   | [<size:10>add <&plus>] |*
    }
    {#
      | <b>No |     <b>Material No     | <b>Suffix |                   <b>Material Name                   |     <b>Parent Mat     | <b>Supplier ID  |                   <b>Supplier Name                   | <b>L | <b>W | <b>H | <b>wt/pc | <b>Qty | <b>Total Wt | <b>Action |*
      '|    || AB12CD34EF             | 00        | Outer Box        | EE-122LX    |             .| TMMIN          | TMMIN             |360    |550    |240    |         .| 1      |           . |*
    }
    No Data Found
    --
    Note :
    {SI
      "                                          "
      .
      .
      .
    }
    .
    {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
    .
    .
    <b>List of Notes:
    --
    <i>No Data Found 
  }
}
@endsalt
@enduml
