@startuml
@startsalt
{
  <b><size:20>CPS - New |[<size:25><&x>]|*
  ==
  {
    {
      <b>CPS No.      |: {|" CPS230220250001A  "|}
      <b>Ref CPS No.  |: {|"                   "| [<&magnifying-glass>]}| *
      Issue  Date     |: {|" 23 Feb 2025       "| [<&calendar>]|}
      Effective Date  |: {|" 01 Mar 2025       "| [<&calendar>]|}
      .
      DPI No.         |: {|" DP2302250001      "| [<&magnifying-glass>]}| *
      CFC/PJT Code    |: {|" CF2025020001      "| [<&magnifying-glass>]}
      Model           |: {|" DX01UB            "| [<&magnifying-glass>]}
      Part No         |: {|" 25051BZ260-00     "| [<&magnifying-glass>]}
    }
    --
    {
      .|.|Part Name   |: | CONVERTER SUB-ASSY, EXHAUST MANIFOLD        |*
      .|.|Supplier    |: | FUTABA INDONESIA      |*
      .|.|Plant Code  |: | AI01                  |*
      .|.|Dock Code   |: | AI-D-001              |*

    }
    {*
      <b><size:14> <&chevron-right> PSE Info
    }
    --
    {*
      <b><size:14> <&chevron-right> Images
    }
    --
    {*
      <b><size:14> <&chevron-bottom> Packing
    }
    --
    {
      <b>OUTER
      { Module Type     |: |"      " | [<&magnifying-glass>] | }*  
      {
        .| Dimension     |: | 00 | x | 00 | x | 00 | cm <sup>3</sup> |*
        .| Inner         |: | 00 | m<sup>3</sup>                      |*
        .| Outer         |: | 00 | m<sup>3</sup>                      |*
      }
    }
    --
    {
      |<b>INNER   | [<size:10>add <&plus>] |*
    }
    {#
      |<b> Pack Material No     |<b> Suffix |<b> Name      |<b> Parent    |<b> Supplier ID |<b> Supplier Name |<b> L  |<b> W  |<b> H  |<b> Wt/PC |<b> Qty |<b> Total Wt |*
    }
    No Data Found
    --
    Note :
    {SI
      "                                          "
      .
      .
      .
    }
    .
    {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
    .
    .
    <b>List of Notes:
    --
    <i>No Data Found 
  }
}
@endsalt
@enduml
