@startsalt
{
  <size:25>CPS List |[<size:25><&x>]|*
  ==
  {
    .|CPS No            |: |"                           "|                    |.|.|DPI No        |: |"                      "|*|*
    .|Ref CPS No        |: |"                           "|                    |.|.|CFC / Pjt       |: |"                      "|*|*
    .|From              |: |"                           "|                    |.|.|Model         |: |"                      "|*|*
    .|Issued Date       |: {|"            "|' to '|"           "|}            |.|.|To            |: |"                      "|*
    .|Effective Date    |: {|"            "|' to '|"           "|}            |.|.|Status        |: | ^Any^Draft^Submitted^Rejected^Approved^ |* {[Search]|  [Clear] }*
  }
  .
  .
  .
  {   
    {[Create CPS] | [Create PSI]|.|.                |.           |                        [Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|} *
    {
      --
      {+
          {#
            |<b> CPS No. |<b> Ref CPS No. |<b> DPI No |<b> Issued Date  | <b>Effective Date |<b> CFC / Pjt   |<b> Model  |<b> # Parts        |<b> From               |<b> To                 |<b> Status       |<b>     Action   |*|*|*
            }
            No Data Found
      }
    }
  }
  --
  {
  << <  __1__  > >>  |'      3 <&chevron-bottom> per page |*
  }  
}
@endsalt
