@startuml
@startsalt
{
  <b><size:20>CPS - New |[<size:25><&x>]|*
  ==
  {
    {
      CPS No.      |:{|"                "|}|*
      Ref CPS No.  |:{|"                "| [<&magnifying-glass>]}| *
      CFC/Model Code  |:{|"         "| [<&magnifying-glass>]}|*
    }
    {
      |      Project           |.|      |:|.|*
      |      Impl. Period      |.|      |:|.|*
    }   
    { 
      Part No         |.|            :{|"         "| [<&magnifying-glass>] | [<&spreadsheet>]}
    }
    {
      |      Part Name        |.|        |:|.|*
      |      Supplier         |.|        |:|.|*
    }
    --
    {*
      <b><size:14> <&chevron-right>Logistic Information
    }
    --
    {*
      <b><size:14> <&chevron-right>PSE Information
    }
    --
    {*
      <b><size:14> <&chevron-right>Images
    }
    --
    {*
      <b><size:14> <&chevron-right>Packing                                                                                                                                                                                                    
      '| <b>No |     <b>Material No     | <b>Suffix |                   <b>Material Name                   |     <b>Parent Mat     | <b>Supplier ID  |                   <b>Supplier Name                   | <b>L | <b>W | <b>H | <b>wt/pc | <b>Qty | <b>Total Wt | <b>Action |*
    }
    --
    Note :
    {SI
      "                                          "
      .
      .
      .
    }
  }
  {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
  .
  .
  <b>List of Notes:
  --
  <i>No Data Found   
}
@endsalt
@enduml
