@startuml
@startsalt
{
  <b><size:20>CPS - New |[<size:25><&x>]|*
  ==
  {
    {
      <b>CPS No.      |: {|"                "|}|*
      <b>Ref CPS No.  |: {|"                "| [<&magnifying-glass>]}| *
      Issue  Date     |: {|"                "| [<&calendar>]|}
      Effective Date  |: {|"                "| [<&calendar>]|}
      .
      DPI No.         |: {|"                "| [<&magnifying-glass>]}| *
      CFC/PJT Code    |: {|"                "| [<&magnifying-glass>]}
      Model           |: {|"                "| [<&magnifying-glass>]}
      Part No         |: {|"                "| [<&magnifying-glass>]}
    }
    {
      .|.|Part Name   |: ||*
      .|.|Supplier    |: {||}
    }
    {*
      <b><size:14> <&chevron-right> PSE Info
    }
    --
    {*
      <b><size:14> <&chevron-right> Images
    }
    --
    {*
      <b><size:14> <&chevron-right> Packing
    }
    --
    Note :
    {SI
      "                                          "
      .
      .
      .
    }
  }
  {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
  .
  .
  <b>List of Notes:
  --
  <i>No Data Found   
}
@endsalt
@enduml
