/.
When duplicate button invoke in the table row, a new row will appear below it
and the CPS No will still be empty because the data hasn't been saved yet,
the Create CPS and Create PSI button will be hidden and Save and Cancel button 
will now appear under the table.
User can whether edit the new duplicated CPS, save it or delete it right away
if user choose to edit it, it will then open edit CPS form.
if user choose to save it, then the CPS No will still be empty but the status will be Draft
if user choose to delete it, then the save/cancel button will dissapear
and the create CPS and Create PSI button will reappear.
./
@startsalt
{
  <size:25>CPS List |[<size:25><&x>]|*
  ==
  {
    .|CPS No            |: {|"                   "|[<&magnifying-glass>] |}.|.                 |DPI No          |: |"                   "|[<&magnifying-glass>]|*
    .|Ref CPS No        |: {|"                   "|[<&magnifying-glass>] |}.|.                 |CFC / Pjt       |: |"                   "|[<&magnifying-glass>]|*
    .|Model             |: {|"             "|[<&magnifying-glass>]|}*
    .|From              |: {|"                 "|[<&people>]           |}.|.|To                |: |"                 "|[<&people>]|*
    .|Issued Date       |: {|"         "|[<&calendar>]|' to '|"         "|[<&calendar>]|}|*
    .|Effective Date    |: {|"         "|[<&calendar>]|' to '|"         "|[<&calendar>]|}|.|.  |Status        |: {| ^Any^Draft^Submitted^Rejected^Approved^ |.|.|.|..||[Search]|  [Clear] }*
  }
  .
  .
  .
  {   
    '{[Create CPS] | [Create PSI]|}*
    {
      --
      {+
          {#
            |<b> CPS No. |<b> Ref CPS No. |<b>DPI No|<b> Issued Date|<b>Effective Date|<b> CFC/Pjt   |<b> Model  |<b> # Parts        |<b> From               |<b> To                 |<b> Status       |<b>  Action   |*|*|*
            |D38403403   |A58503112       |D38403403|21 Jun 2025    |21 Jun 2025      |D54B          | D60B      | 2                 | Khedi Asmoro (PSE)    |  Cecep Gunadi (Aisin) |  Submitted      | .|.|.|*
            |.           |D38403403       |D38403403|D21 Jun 2025   |21 Jun 2025      |D54B          | D60B      | 2                 | Khedi Asmoro (PSE)    | .                     |  Draft          | [<&pencil>]|.|[<&trash>]|*
          }
      }
    }
  }
  --
  {[Save] | [Cancel]|}*
  --
  {
  << <  __1__  > >>  |'      3 <&chevron-bottom> per page |*
  }  
}
@endsalt
