@startsalt
{
  <size:25>DPI List |[<size:25><&x>]|*
  ==
  {
      .|DPI No            |: |"                      "|             |.|.|CFC/Pjt   |: |"               "|*|*
      .|Ref DPI No        |: |"                    "|               |.|.|Model     |: |"               "|*|*
      .|From              |: |"                    "|               |.|.|To        |: |"               "|*|*
      .|Issued Date       |: {|"21.06.2025"|' to '|"21.06.2025"|}   |.|.|Status  |: | {.| ^Any^Draft^Submitted^Rejected^Approved^}|       .                  '| [Search <&magnifying-glass>] |*      
      .|Effective Date    |: {|"21.06.2025"|' to '|"21.06.2025"|}
  }
  .
  .
  {
    {
      --
      {+
        {#
          |.|<b> DPI No.        |<b> Ref DPI No. |<b> Issued Date  | <b>Effective Date |<b> CFC/Pjt        |<b> Model  |<b> # Parts |<b> # CPS |<b> From               |<b> To                |<b> Status          |<b> Action |*|*
          |<b> <&chevron-bottom>|D38403403       |A58503112        |23 Feb - 2025      | 01 Mar - 2025     |D54B          | D60B      | 2          | 1                 |Andi Nuridwan (PPM)   | Khedi Asmoro (PSE) |     Submitted   | [<&pencil>]|[<&trash>]|*          
        }
        {
          .|.|.|{#
            |<b>Part No          |<b> Part Name                |<b> Supp Code |<b> Supp Name         | <b> CPS No. |<b> Ref CPS No. |<b> Issued Date | <b>Effective Date |<b> Status       |<b> Action |*|*
            |33504-BZ292-C1      |KNOB SUB-ASSY, SHIFT LEVER   |5368-1        |MTAT INDONESIA        |D38403403    |A58503112       |23 Feb - 2025   | 01 Mar - 2025     |     Submitted   | [<&flash>]|.|*
            |45130-BZ890-C0      |PAD ASSY, STEERING WHEEL     |5626-1        |TOYODA GOSEI INDONESIA|.            |.               |.               |.                  |     Draft       | [<&flash>]|.|*
          }
        }
      }
    }
  }
  --
  {
  << <  __1__  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
