@startuml
@startsalt
{+
  .|{
    <b><size:20>CPS - New |[<size:25><&x>]|*
    ==
    {
      !include ../components/form-header-filled.puml
      --
      !include ../components/logistic-section-collapsed.puml
      --
      !include ../components/pse-section-collapsed.puml
      --
      !include ../components/packing-images-filled-expanded-rw.puml
      --
      !include ../components/packing-section-filled-expanded-rw.puml
      --
      Note :
      {SI
        "                                          "
        .
        .
        .
      }
    }
    {[Save <&media-record>] | [Submit <&data-transfer-upload>]}
    .
    .
    <b>List of Notes:
    --
    <i>No Data Found     
  }
}
@endsalt
@enduml
