{#
  !include cps-list-tbl-header-content-only.puml
  '|                    |                    |                  |                 |              |                |                           |                           |                   |                   |*|*|*
}