  {
    {
      CPS No.         |:{|CPS 301B DB01UB 25051BZ26000|}
      Ref CPS No.     |:{|                   |}| *      
      CFC Model       |:{|DX01UB      |}
    }
    {
      |     |Destination     |:| 301B - Thailand |*
      |     |Project Code    |:| 118D |*
    }
    {
      Part No         |:{|25051BZ260-00 | [<&spreadsheet>]}
    }
    {
      |     Part Name       |: | CONVERTER SUB-ASSY, EXHAUST MANIFOLD        |*
      |     Supplier        |: | 5008 - KOMPONEN FUTABA       |*
    }    
    --
  }