@startsalt
{
  {
    |<b>INNER   | [<size:10>add <&plus>] |*
  }
  {#
    !include ./inner-tbl-header.puml
    |   1   | AB12CD34EF             |   00      | Outer Box                                            | EE-122LX     |                    .| TMMIN           | ^ Supplier^    | TMMIN                                                 | 360    | 550   | 240  | "     "| "  1"  |           . | "    20"    |[<&document>]|.             |[<&pencil>]|[<&trash>]|*
    |   2   | GH56IJ78KL             |   00      | Carton Sheet                                         | FF-FTB       |                    .| TMMIN           | ^  TMMIN  ^    | TMMIN                                                 |.       |.      |.     |       .| "  1"  |           . | "  180 "    |[<&document>]|[<&document>] |[<&pencil>]|[<&trash>]|*
    |   3   | MN90OP12QR             |   00      | Plastic Sheet   '                                    | DD-5G        |                    .| TMMIN           | ^ Supplier^    | TMMIN                                                 |.       |.      |.     | "     "| "  1"  |           . | "    50"    |[<&document>]|[<&document>] |[<&pencil>]|[<&trash>]|*
    |   4   | ST34UV56WX             |   00      | Anti Rust                                            | AA622F       |                    .| TMMIN           | ^  TMMIN  ^    | TMMIN                                                 |.       |.      |.     |       .| "  2"  |           . | "    60"    |[<&document>]|[<&document>] |[<&pencil>]|[<&trash>]|*
  }
}