{
  |TMMIN Dest Dock Code     |: {| " "|[<&magnifying-glass>]}|*
  |Remark                   |: {SI
                                "                                                 " 
                                .
                                .
                               }|*
  |Process Type             |: {|(X)N|.  '|()W|.  '|()X|.  '|()Y|.|}*
  |Address Rack             |: |"     "|*
}