{  
  {
    |<b>OUTER   |[<size:10>add <&plus>] |*
  }
  {#
    !include ./outer-tbl-header.puml
    |   1   | AB12CD34EF             |   00      | Outer Box                                            | E122L        |                    .| TMMIN          | TMMIN                                                 | 360    | 550   | 240  |         .| "   1" |           . |[<&pencil>]|[<&trash>]|*
    |   2   | GH56IJ78KL             |   00      | Carton Sheet                                         | FFFT         |                    .| TMMIN          | TMMIN                                                 |.       |.      |.     |         .| "   1" |           . |[<&pencil>]|[<&trash>]|*
    |   3   | MN90OP12QR             |   00      | Plastic Sheet   '                                    | DD25G        |                    .| TMMIN          | TMMIN                                                 |.       |.      |.     |         .| "   1" |           . |[<&pencil>]|[<&trash>]|*
    |   4   | ST34UV56WX             |   00      | Anti Rust                                            | AA622        |                    .| TMMIN          | TMMIN                                                 |.       |.      |.     |         .| "   2" |           . |[<&pencil>]|[<&trash>]|*      
  }
}