| <b>No |       <b>Item No       | <b>Suffix |                   <b>Material Name                   |   <b>eWh ItemNo  | <b>Supplier ID  |                   <b>Supplier Name                   | <b>L   | <b>W  | <b>H | <b>wt/pc | <b>Qty | <b>Total Wt | <b>Document |*|    <b>Action   |*|*