@startsalt
{
  {*
    <b><size:14> <&chevron-bottom> Packing
  }
  --
  {
    {
      |Part Weight      |: |" 300"|*
      |Packing Weight   |: |" 330"|*
      |Packing Qty      |: |"   3"|*
      |Pcs/Kanban       |: |"   5"|*
    }*
    {
      |Damage Test Doc |:  |<size:50><&document>|*
      |                |[change]|*
    }
    .
    <b>OUTER
    --
    {|Module |(X)|      |Mesh Pallet|()|}*
    --
    {
      {      Module Type     |: |" T1B TAR "| [<&magnifying-glass>] | }*  
        {
          .|       Dimension     |: | 80 | x | 60 | x | 50 | cm <sup>3</sup> |*
          .|       Inner         |: | 1,50 | m<sup>3</sup>                      |*
          .|       Outer         |: | 1,55 | m<sup>3</sup>                      |*        
        }
    }
  }
  --
  {
    |<b>OUTER   | [<size:10>add <&plus>] |*
  }
  {#
    !include ./outer-tbl-header.puml
    |   1   | AB12CD34EF             |   00      | Outer Box                                            | EE-122LX     | TMMIN          |  TMMIN                                                 | 360    | 550   | 240  |    200   | "  1"|       200|[<&document>]|[<&document>] |[<&pencil>]|[<&trash>]|*
    |   2   | GH56IJ78KL             |   00      | Carton Sheet                                         | FF-FTB       | TMMIN          |  TMMIN                                                 |.       |.      |.     |         .| "  1"|.         |.            |[<&document>] |[<&pencil>]|[<&trash>]|*
    |   3   | MN90OP12QR             |   00      | Plastic Sheet   '                                    | DD-5G        | TMMIN          |  TMMIN                                                 |.       |.      |.     |         .| "  1"|.         |.            |[<&document>] |[<&pencil>]|[<&trash>]|*
    |   4   | ST34UV56WX             |   00      | Anti Rust                                            | AA622F       | TMMIN          |  TMMIN                                                 |.       |.      |.     |         .| "  2"|.         |[<&document>]|[<&document>] |[<&pencil>]|[<&trash>]|*    
  }
}