  {*
    <b><size:14> <&chevron-right>Packing                                                                                                                                                                                                    
    '| <b>No |     <b>Material No     | <b>Suffix |                   <b>Material Name                   |     <b>Parent Mat     | <b>Supplier ID  |                   <b>Supplier Name                   | <b>L | <b>W | <b>H | <b>wt/pc | <b>Qty | <b>Total Wt | <b>Action |*
  }