{
  {*
    <b><size:14> <&chevron-bottom> PSE Info
  }
  'pse inputed fields
  { 
    {
      |<b>    Packing Plant |*        |  .      | <b>       Vanning Plant |*             |*
      |Curr  :          |{ ^  STR 1^ }|  .      |Curr  :           |{ ^  STR 1^ }      |*
      |Next  :          |{ ^  STR 1^ }|  .      |Next  :           |{ ^  STR 1^ }      |*      
    }
    .
    {
      {Category       |:| { ^   TRIM^ }|}*
    }
    {
      Importer Line Process   '|:|^   TRIM^^|*
      Case Code                |:|" IM "|*
      Box Number               |:|"  A1"|"  A2"|"  A3"|*
      Renban                   |:|"  L"|*
      Packing Line             |:|"  AP"|*
      {
        |<b>Packing Process |*        |* 
        . |Boxing    :          |{ ^   TMMIN^ }|*  
        . |Stacking  :          |{ ^SUPPLIER^ }|*  
      }
    }
  }
  --
  {
    |<b>OUTER   |[<size:10>add <&plus>] |*
  }
  {#
    !include ./outer-tbl-header.puml
    |   1   | AB12CD34EF             |   00      | Outer Box                                            | EE-122LX     | TMMIN          | TMMIN                                                 | 360    | 550   | 240  |         .| "  1"|           . |[<&pencil>]|[<&trash>]|[<&image>]|*
    |   2   | GH56IJ78KL             |   00      | Carton Sheet                                         | FF-FTB       | TMMIN          | TMMIN                                                 |.       |.      |.     |         .| "  1"|           . |[<&pencil>]|[<&trash>]|[<&image>]|*
    |   3   | MN90OP12QR             |   00      | Plastic Sheet   '                                    | DD-5G        | TMMIN          | TMMIN                                                 |.       |.      |.     |         .| "  1"|           . |[<&pencil>]|[<&trash>]|[<&image>]|*
    |   4   | ST34UV56WX             |   00      | Anti Rust                                            | AA622F       | TMMIN          | TMMIN                                                 |.       |.      |.     |         .| "  2"|           . |[<&pencil>]|[<&trash>]|[<&image>]|*      
  }
}
