@startsalt
{
  <size:15><b>Module Type New|[<size:25><&x>]|*
  ==
  .

  {
  {   
    .|Type Code         |: |"          "|*
    .|Item No           |: |"              "| [Search] |* 
    .|E-Warehouse Price |: |          |*
    .|Dim  Outer (mm<sup>3</sup>) |: {'  L:|"  "|W:|"  "|H:|"  "|}|*
    .|Dim  Outer (m<sup>3</sup>)  |: |*
    .|Dim  Inner (mm<sup>3</sup>) |: {'  L:|"  "|W:|"  "|H:|"  "|}|*
    .|Dim  Inner (mm<sup>3</sup>) |: |*
  }
  --
{
|Dest Code |: |^301B - Argentina ^ 807B - Indonesia ^ 537B - Afrika^|*
.
.   
|Price     |: |"            "|
}
    
  }
--  
{
  .|  [Save <&data-transfer-download>] |  [Cancel <&circle-x>] |*
  }
}

  @endsalt