@startsalt
{
  <size:15><b>Module Type List|[<size:25><&x>]|*
  ==
  .
  {
      .|Type Code    |: |"                      "|*
      .|Item No      |: |"                      "| [Filter <&magnifying-glass>]| [Clear <&x>]| *      

  }
  --
  {
  [Add <&document>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
   {#
  |<b> Type Code |<b>  Dest Code  |<b>  Dest Name  |<b>  Item No  | <b> Dimension (cm)  |<b> Outer (m<sup>3</sup>) |<b> Inner (m<sup>3</sup>) | <b>#  Price  |<b>     Action |*|*|*
  |  T3A - TAR   |       301B     |     Argentina  | DX09TY       |  2250 x 1490 x 860  |      14.4                |        2,37              |   5.000.000  |[<&pencil>]|[<&delete>]|[<&layers>]|*

  } 
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
@enduml
