@startsalt
{
  <size:15><b>Module Type List|[<size:25><&x>]|*
  ==
  .
  {
      .|Type Code    |: |"                      "|*
      .|Item No      |: |"                      "| [Filter <&magnifying-glass>]| [Clear <&x>]| *      

  }
  --
  {
  [Add <&document>]|.|.|.|[Upload <&data-transfer-upload>]| [Template <&data-transfer-download>]|*
  }
  --
  {#
  |                . |<b> Type Code  |<b>  Item No  '|<b> Dimension (cm)  |<b> Outer (m<sup>3</sup>) |<b> Inner (m<sup>3</sup>)   | <b># Dest |<b>     Action |*|*|*
  | <&chevron-bottom> |   BX1B        | DX09TY        | 30 x 40 x 12       |          14.4            | 200                        |        3 |[<&pencil>]|[<&delete>]|[<&layers>]|*
  }
  {.|.|.|
    {#
    |<b>Dest Code|<b> Dest Country|     <b>Price|*
     |   301B    |Argentina       |  4.350.000|*
     |   537B    |Afrika          |  4.350.000|*
     |   722C    |Thailand        |  1.230.000|*
    }*
  }
  {#
  |                . |<b> Type Code  |<b>  Item No  '|<b> Dimension (cm)  |<b> Outer (m<sup>3</sup>) |<b> Inner (m<sup>3</sup>)   | <b># Dest |<b>     Action |*|*|*
  | <&chevron-right> |   BX2C        | DX10TY        | 32 x 42 x 14       |          12.2            | 210                        |        1 |[<&pencil>]|[<&delete>]|[<&layers>]|*
  | <&chevron-right> |   BX3D        | DX11TY        | 35 x 45 x 15       |          10.7            | 220                        |        1 |[<&pencil>]|[<&delete>]|[<&layers>]|*
  }|
  --
  {
  << <  __1__ 2 3  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
@enduml
