@startsalt
{
  <size:15><b>Module Type|[<size:25><&x>]|*
  ==
  .
  {   
    .|Type Code      |: |"          "|*
    .|Item No        |: |"               "| [Search] |* |[Clear] |*
    .|Dim  Outer (mm<sup>3</sup>) |: {'  l:|"  "|w:|"  "|h:|"  "|}|*
    .|Dim  Outer (m<sup>3</sup>)  |: |*
    .|Dim  Inner (mm<sup>3</sup>) |: {'  l:|"  "|w:|"  "|h:|"  "|}|*
    .|Dim  Inner (mm<sup>3</sup>) |: |*
  }
  .
--  
{
  .|  [Save <&data-transfer-download>] |  [Cancel <&circle-x>] |*
  }
}

  @endsalt