@startsalt
{
  <size:25>DPI List |[<size:25><&x>]|*
  ==
  {
      .|DPI No            |: |"                      "|               |.|.|CFC/Pjt   |: |"               "|*|*
      .|Ref DPI No        |: |"                      "|               |.|.|Model   |: |"               "|*|*
      .|From              |: |"                      "|               |.|.|To      |: |"               "|*|*
      .|Issued Date       |: {|"       "|' to '|"       "|}           |.|.|Status  |: | {.| ^Any^Draft^Submitted^Rejected^Approved^}|    '|.| [Search] |  | [Clear] |*    
      .|Effective Date    |: {|"       "|' to '|"       "|}
  }
  .
  .
  {   
    {
      --   
      {+
        {#
          |.                  |<b> DPI No.  |<b> Ref DPI No. |<b> Issued Date  | <b>Effective Date |<b> CFC/Pjt   |<b> Model  |<b> # Parts |<b> # CPS |<b> From              |<b> To              |<b> Status       |<b> Action |*|*
        }
        No Data Found
      }
    }
  }
  --
  {
  << <  __1__  > >>  |'      3 <&chevron-bottom> per page |*
  }
}
@endsalt
