@startsalt
{
  <size:15><b>Supplier - New |[<size:25><&x>]|*
  ==
  
  {   
    .|Supplier Code |: |"5062   "|*
    .|Supplier Name |: |"MENARA TERUS MAKMUR  "|*
    .|Address       |: |"Jalan Jababeka XI Kawasan Industri Jababeka No.12, Blok H3"
    .|.             |: |"Harja Mekar, Kec. Cikarang Utara, Kab Bekasi, Jawa Barat 17530"|*
  }
  --
  {
  .|[ Save <&data-transfer-download>] |  [Cancel <&circle-x> ]|*
  }
}

  @endsalt
